@baseUrl = http://localhost:8000/api
@token = Bearer 161|krKrdk2fqEu7JRXnRgril1WkKjsHC4UIOphHVktse771d67f

### Listar Comentarios
GET {{baseUrl}}/comentarios
Authorization: Bearer {{token}}
Accept: application/json

### Crear Comentario
POST {{baseUrl}}/comentarios
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "tema_id": 6,
    "cuerpo": "Los Increibles, lo mejor"
}

### Editar Comentario
PUT {{baseUrl}}/comentarios
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "id": 9,
    "cuerpo": "Me gusta El Conjuro 1, 2 y 3"
}

### Eliminar Comentario
DELETE {{baseUrl}}/comentarios/10
Authorization: Bearer {{token}}
Accept: application/json