### Variables Globales
@baseUrl = http://127.0.0.1:8000/api
@token = 219|lm4QqrJqaQ5bsj0GhtlqYLghuB2WXgAXotTfof2E9d4a795b

### 1. Listar Blogs (Ordenados del más reciente al más viejo)
GET {{baseUrl}}/blog/index
Authorization: Bearer {{token}}
Accept: application/json

### 2. Crear Nuevo Evento Crítico (Store)
POST {{baseUrl}}/blog/store
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "usuario_reporte_id": 1,
    "titulo": "xzxsak jcjdfj ksldjsjd lkjdksajkl lsadj lksjslkdjsakl sakldjsaklj",
    "prioridad": "Media",
    "estado": "En Progreso"
}

### 3. Editar Evento (Cambiar a Cerrado)
POST {{baseUrl}}/blog/edit
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "id": 17,
    "titulo": "Tripin de pollin revolution",
    "prioridad": "Baja",
    "estado": "Cerrado"
}

### 5. Eliminar un Evento (Destroy)
DELETE {{baseUrl}}/blog/delete/13
Authorization: Bearer {{token}}
Accept: application/json